[build]
  command = "npm run build:demo"
  publish = "demo/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    cache-control = "no-cache"

[[headers]]
  for = "/index.html"
  [headers.values]
    cache-control = "no-cache"

[[headers]]
  for = "/"
  [headers.values]
    cache-control = "no-cache"
